### ISSUE TITLE
Erreur Gulp

### ISSUE THREAD

**Issue by hiwelo** [alsacreations/bretzel#26]
À l'exécution d'une tâche `gulp`, j'ai une erreur qui apparaît : 
```
Error: Cannot find module 'gulp-uncss'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/damien/Sites/bretzel/gulpfile.js:22:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
La dépendance `gulp-uncss` a été retirée du fichier `package.json` mais la tâche existe toujours.

**Comment by raphaelgoetter** [comment]
Oui la tâche existe toujours.

L'idée était de ne plus charger systématiquement unCSS via `npm install` car long et souvent inutile.

Par contre je pensais laisser la tâche au cas où, en me disant que - forcément - si on veut l'appliquer, il faut l'ajouter dans le package.
Ce n'est sans doute pas assez clair effectivement.

Proposition : 
- on commente aussi la tâche et on rajoute un warning : "il faut ajouter dans le package d'abord"
- on supprime complètement unCSS

Je suis open.

**Comment by PhilippeVay** [comment]
Je serais partisan de supprimer la tâche vu qu'on ne s'en sert pas. Ou de la déplacer donc question : quel serait le moyen le plus sioux d'utiliser Uncss sans l'ajouter à la main dans le gulpfile.js dans les rares projets où on va l'utiliser ?
Dans un éventuel gros projet à venir, on l'ajoutera au gulpfile mais sinon dans les projets de taille moyenne ?

**Comment by hiwelo** [comment]
Les deux méthodes (commentaire ou suppression) me vont.
